---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Structural Calculations"
subtitle: "AK"
documentTitle: "Ak-Structural Calculations" # Customize the browser tab text
logo: "assets/tools/logo_colormatch.png"
header: true 
footer: '<p>Contact: <a href="https://portfolio.rpakishore.co.in/">Arun Kishore</a>' # set false if you want to hide it.

columns: "auto" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
connectivityCheck: false 

# Set the default layout and color scheme
defaults:
  layout: columns # Either 'columns', or 'list'
  colorTheme: dark # One of 'auto', 'light', or 'dark'

theme: default # 'default' or one of the themes available in 'src/assets/themes'.

colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#424242"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
    background-image: "assets/your/light/bg.png"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"
    background-image: "assets/your/dark/bg.png"


links:
  - name: "Github"
    icon: "fab fa-github"
    url: "https://github.com/rpakishore"
    target: "_blank" # optional html tag target attribute

  - name: "Status"
    icon: "fas fa-heartbeat"
    url: "https://uptime.rpakishore.co.in/status/structural"
    target: "_blank" # optional html tag target attribute


services:
  - name: "Loadings"
    icon: "fa fa-bolt"
    items:
      - name: "Dead Loads"
        icon: "fa fa-arrow-down"
        subtitle: "Density of typical materials seen in construction"
        url: "https://links.struct.work/Dead-Loads"
        target: "_blank"
      - name: "Snow/Wind Load Station Locator"
        logo: "assets/tools/canada.png"
        subtitle: "Identify closest design stations to GPS coordinates"
        url: "https://links.struct.work/Station-Locator"
        target: "_blank"
        tag: "NBCC 2020"
      - name: "Seismic Design Loads for Rect. Liquid Containing Tanks"
        logo: "assets/tools/water-tank-color.png"
        subtitle: "Based on ACI-350.3-06"
        url: "https://loadings.struct.work/Rect_Tank-Seismic"
        target: "_blank"
        tag: "ACI 350.3-06"
      - name: "Blast Loads"
        icon: "fas fa-bomb"
        subtitle: "Based on UFC-3-340-02"
        url: "https://loadings.struct.work/Blast_loads"
        target: "_blank"
        tag: "UFC-3-340-02"

  - name: "Steel"
    icon: "fas fa-anchor"
    items:
      - name: "Section Properties"
        logo: "assets/tools/steel-section.png"
        subtitle: "Structural steel section properties"
        tag: "CSA"
        url: "https://general.struct.work/Section_properties"
        target: "_blank"
        tagstyle: "is-success"

      - name: "Piping Dimensions & Properties"
        icon: "fa-solid fa-database"
        subtitle: "Std pipe sizes, weights and flowrates"
        url: "https://general.struct.work/Piping_data"
        target: "_blank"
        tag: "ASME B36.10"
        tagstyle: "is-success"

      - name: "Basic Weld Capacity"
        logo: "assets/tools/weld-color.png"
        subtitle: "Calculate the capacity of weld per CSA S16 Cl.13.3"
        url: "https://loadings.struct.work/Weld_capacity"
        target: "_blank"
        tag: "CSA S16-10th ed."
        tagstyle: "is-success"

      - name: "Basic Bolt Capacity"
        logo: "assets/tools/bolt-color.png"
        subtitle: "Calculate the capacity of bolt per CSA S16 Cl.13.3"
        url: "https://loadings.struct.work/Bolt_capacity"
        target: "_blank"
        tag: "CSA S16-10th ed."
        tagstyle: "is-success"

  - name: "Concrete"
    logo: "assets/tools/concrete.png"
    items:
      - name: "Development length"
        logo: "assets/tools/rebar-color.png"
        subtitle: "Tension/Compression/Hooked dev. lengths"
        tag: "CSA A23.3-19"
        url: "https://general.struct.work/Development_length"
        target: "_blank"

      - name: "One-way slab design"
        icon: "fas fa-arrows-v"
        subtitle: "Reinforced concrete slab design per CSA/ACI"
        url: "https://slabs.struct.work/"
        target: "_blank"
        tagstyle: "is-info"
        tag: "Proof of Concept Calc"

  - name: "Browser Add-ons"
    logo: "assets/tools/browser.png"
    items:
      - name: "Hilti Profis Aid"
        logo: "assets/tools/hilti.png"
        subtitle: "Helpful recommendations to mitigate anchor failure"
        tag: "Javascript"
        url: "https://github.com/rpakishore/hilti-profis-help"
        target: "_blank"

